controller_manager:
  ros__parameters:
    update_rate: 10

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    motor_controller:
      type: forward_command_controller/ForwardCommandController

motor_controller:
  ros__parameters:
    joints:
      - motor_joint
    interface_name: velocity